apiVersion: apps/v1  
kind: Deployment
metadata:
  name: secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
        - name: app
          image: nodejs-secret-app:latest
          imagePullPolicy: Never         
          ports:
            - containerPort: 3000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_KEY
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DB_PASS

