apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: demo-container
      image: nginx
      env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_PORT
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_ENV
