apiVersion: v1
kind: Service
metadata:
  name: my-k8s-app
spec:
  type: NodePort
  selector:
    app: my-k8s-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32570
apiVersion: v1
kind: Service
metadata:
  name: my-k8s-app
spec:
  type: NodePort
  selector:
    app: my-k8s-app
  ports:
    - protocol: TCP
      port: 3000        # service port
      targetPort: 3000  # container port
